### ISSUE TITLE
Please specify a license

### ISSUE THREAD

**Issue by mikaelhg** [RovoMe/JDiff#1]
Would you mind specifying the license you had in mind for the reuse of the repository, please?

The standard way to do that is to copy a license file as `/LICENSE`.

**Comment by RovoMe** [comment]
Hi Mikael,

sorry for my late response. Somehow the notification system at Github isn't working for me currently.

I'm not an expert on licensing formats as I didn't ever define one (and didn't care to). Based on http://choosealicense.com/ I'd be in favor for MIT just for its simplicity. If this does not work for you, please suggest any.

**Comment by mikaelhg** [comment]
MIT works fine for me.

**Comment by benloud** [comment]
Your license file does not include your name and the year. Can you please fill them in.
